export { NavbarComponent } from "./navbar/navbar.component";
export { MenuComponent } from "./menu/menu.component";
export { GalleryComponent } from "./gallery/gallery.component";
export { BookingComponent } from "./booking/booking.component";
export { ContactComponent } from "./contact/contact.component";
export { HomeComponent } from "./home/home.component";
export { SidenavComponent } from "./admin/sidenav/sidenav.component";
export { DashboardComponent } from "./admin/dashboard/dashboard.component";
export { MenuPanelComponent } from "./admin/menu-panel/menu-panel.component";
export { GalleryPanelComponent } from "./admin/gallery-panel/gallery-panel.component";
export { AboutComponent } from "./about/about.component";
export { LoginComponent } from "./account/login/login.component"
export { RegisterComponent } from "./account/register/register.component";
export { ProfileComponent } from "./account/profile/profile.component";